services:
  backend:
    build: backend
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=localhost
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=nest-postgres
    networks:
      - server-side
    volumes:
      - ./backend:/backend/app
      - /backend/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/srv/dev-disk-by-id-md-name-r2d2-1/home/sergeylys/work/postgresql/data

networks:
  server-side: { }

volumes:
  db-data: { }
